# Generated by Django 3.2.19 on 2023-05-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('scam', 'Scam'), ('helpful', 'Helpful')], max_length=10)),
                ('description', models.TextField()),
                ('report_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('aggregate_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_country', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=100)),
                ('evidence', models.FileField(blank=True, upload_to='scam_reports/')),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('investigator_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('social_media_accounts', models.ManyToManyField(to='hcs.SocialMediaAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
